name: Discord Test

on:
  push:
    branches: [ master ]

jobs:

  release-notification:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-notifications@develop
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}
          title: PMM Overlay Reset Release VERSION
          message: "A new version of PMM Overlay Reset has been released and is available to all users"
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png