name: Commit Notiyfication

on:
  push:

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-notifications@master
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}
          title: Plex Meta Manager Develop Commity
          commits: "true"
          username: PMM Develop
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png