name: Release

on:
  release:
    types: [ published ]

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-release-action@3996630fad0dba74035d1a49237a79dbd3cc28d9
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}
