name: Discord Notification Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker-develop:
    runs-on: ubuntu-latest
    steps:

      - name: Discord Success Notification
        uses: meisnate12/discord-notifications@ce53473b19eb488d5ba96e577cef9b8a94ad057f
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "Docker develop build: **Success**"
          username: Docker
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/docker.png
