name: Release

on:
  release:
    types: [ published ]

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-release-action@d45d1d320773f2db5dde5d1e7c4024c19bbc4fbd
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}
