name: release

on:
  push:
    branches: [ master ]

jobs:

  docker-version:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changelog
        id: notes
        run: |
          NOTE=$(cat CHANGELOG)
          echo 'NOTES=$NOTE' >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.notes.outputs.NOTES }}
          token: ${{ secrets.PAT }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}