name: "release"

on:
  create:
    tags:
      - v*

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          prerelease: false
          title: "Release ${{ github.event.ref }}"
