name: release

on:
  push:
    branches: [ master ]

jobs:

  docker-version:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: salsify/action-detect-and-tag-new-version@v1.0.3
        id: tag
        with:
          version-command: |
            cat VERSION

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG
          token: ${{ secrets.PAT }}
          tag_name: ${{ steps.tag.outputs.tag }}